
package Vista;

import ejercicio2.*;
import Excepciones.*;
import java.util.regex.Matcher;
import java.util.regex.Pattern;
import javax.swing.JOptionPane;

/**
 * @author asier
 */
public class Datos extends javax.swing.JFrame {

    /**
     * Creates new form Mostrar
     */
    public Datos() {
        initComponents();
        setLocationRelativeTo(null);
        jLnombre.setVisible(false);
        jLapellidos.setVisible(false);
        jLdni.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jTnombre = new javax.swing.JTextField();
        jTapellidos = new javax.swing.JTextField();
        jTdni = new javax.swing.JTextField();
        jBaceptar = new javax.swing.JButton();
        jBsalir = new javax.swing.JButton();
        jLnombre = new javax.swing.JLabel();
        jLapellidos = new javax.swing.JLabel();
        jLdni = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel1.setText("ALTA DE PERSONAS");

        jLabel2.setText("Nombre:");

        jLabel3.setText("Apellidos");

        jLabel4.setText("DNI:");

        jTnombre.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jTnombreFocusGained(evt);
            }
        });
        jTnombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTnombreActionPerformed(evt);
            }
        });

        jTapellidos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTapellidosActionPerformed(evt);
            }
        });

        jTdni.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTdniActionPerformed(evt);
            }
        });

        jBaceptar.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jBaceptar.setText("Aceptar");
        jBaceptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBaceptarActionPerformed(evt);
            }
        });

        jBsalir.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jBsalir.setText("Salir");
        jBsalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBsalirActionPerformed(evt);
            }
        });

        jLnombre.setForeground(new java.awt.Color(255, 0, 0));

        jLapellidos.setForeground(new java.awt.Color(255, 0, 0));

        jLdni.setForeground(new java.awt.Color(255, 0, 0));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(74, 74, 74)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(37, 37, 37)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel4))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(19, 19, 19)
                                        .addComponent(jTdni, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jLdni))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(18, 18, 18)
                                        .addComponent(jTnombre, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(11, 11, 11)
                                        .addComponent(jLnombre))))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addGap(18, 18, 18)
                                .addComponent(jTapellidos, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLapellidos)))))
                .addContainerGap(89, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(75, 75, 75)
                .addComponent(jBaceptar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jBsalir)
                .addGap(76, 76, 76))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addComponent(jLabel1)
                .addGap(40, 40, 40)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jTnombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLnombre))
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jTapellidos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLapellidos))
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jTdni, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLdni))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jBaceptar)
                    .addComponent(jBsalir))
                .addContainerGap(26, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTnombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTnombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTnombreActionPerformed

    private void jTapellidosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTapellidosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTapellidosActionPerformed

    private void jTdniActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTdniActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTdniActionPerformed

    private void jBaceptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBaceptarActionPerformed
        try{
            
            boolean bDni = ComprobarDni("^[0-9]{8}[A-Z]");
            boolean bApellidos = ComprobarApellidos("^[A-Z][a-z]+( [A-Z][a-z]+)?$");
            boolean bNombre = ComprobarNombre("^[A-Z][a-z]+$");
            if (bNombre == true && bApellidos == true && bDni == true) {
                Ejercicio2.AñadirPersona(jTnombre.getText(), jTapellidos.getText(), jTdni.getText());
                jTnombre.setText("");
                jTapellidos.setText("");
                jTdni.setText("");
                jTnombre.requestFocus();
            }
        }
        catch(Exception e)
                {
                   JOptionPane.showMessageDialog(null, "Problemas");
                }
    }//GEN-LAST:event_jBaceptarActionPerformed

    private void jTnombreFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTnombreFocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_jTnombreFocusGained

    private void jBsalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBsalirActionPerformed
        Ejercicio2.SalirDatos();
        // TODO add your handling code here:
    }//GEN-LAST:event_jBsalirActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Datos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Datos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Datos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Datos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Datos().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBaceptar;
    private javax.swing.JButton jBsalir;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLapellidos;
    private javax.swing.JLabel jLdni;
    private javax.swing.JLabel jLnombre;
    private javax.swing.JTextField jTapellidos;
    private javax.swing.JTextField jTdni;
    private javax.swing.JTextField jTnombre;
    // End of variables declaration//GEN-END:variables
    
    public boolean ComprobarNombre(String expresion) throws Exception{
        boolean correcto = false;
        try {
            if (jTnombre.getText().isEmpty()) {
                throw new DatosIncompletos();
            }
            Pattern pat = Pattern.compile(expresion);
            Matcher mat = pat.matcher(jTnombre.getText());
            if (!mat.matches()) {
                throw new DatoNoValido();
            }
            jLnombre.setVisible(false);
            correcto = true;
        }
        catch (DatoNoValido e)
        {
            jTnombre.requestFocus();
            jLnombre.setText("Nombre no valido");
            jLnombre.setVisible(true);
        }
        catch (DatosIncompletos e)
        {
            jTnombre.requestFocus();
            jLnombre.setText("Nombre obligatorio*");
            jLnombre.setVisible(true);
        }
        return correcto;
    }
    
    public boolean ComprobarApellidos(String expresion) throws Exception{
        boolean correcto = false;
        try {
            if (jTapellidos.getText().isEmpty()) {
                throw new DatosIncompletos();
            }
            Pattern pat = Pattern.compile(expresion);
            Matcher mat = pat.matcher(jTapellidos.getText());
            if (!mat.matches()) {
                throw new DatoNoValido();
            }
            jLapellidos.setVisible(false);
            correcto = true;
        }
        catch (DatoNoValido e)
        {
            jTapellidos.requestFocus();
            jLapellidos.setText("Apellido no valido");
            jLapellidos.setVisible(true);
        }
        catch (DatosIncompletos e)
        {
            jTapellidos.requestFocus();
            jLapellidos.setText("Apellido obligatorio*");
            jLapellidos.setVisible(true);
        }
        return correcto;
    }
    
    public boolean ComprobarDni(String expresion) throws Exception{
        boolean correcto = false;
        try {
            if (jTdni.getText().isEmpty()) {
                throw new DatosIncompletos();
            }
            Pattern pat = Pattern.compile(expresion);
            Matcher mat = pat.matcher(jTdni.getText());
            if (!mat.matches()) {
                throw new DatoNoValido();
            }
            jLdni.setVisible(false);
            for (int i = 0; i < Ejercicio2.listaP.size(); i++) {
                if (jTdni.getText().equals(Ejercicio2.listaP.get(i).getDNI())) {
                    throw new DniExistente();
                }
            }
            correcto = true;
        }
        catch (DniExistente e)
        {
            jTdni.requestFocus();
            jLdni.setText("DNI existente");
            jLdni.setVisible(true);
        }
        catch (DatoNoValido e)
        {
            jTdni.requestFocus();
            jLdni.setText("DNI no valido");
            jLdni.setVisible(true);
        }
        catch (DatosIncompletos e)
        {
            jTdni.requestFocus();
            jLdni.setText("DNI obligatorio*");
            jLdni.setVisible(true);
        }
        return correcto;
    }
}
